### PR TITLE
Moodle28 eventunlocking

### PR DESCRIPTION
**Pull request by kabalin**
As discussed in #8, the pull request contains events unlocking implementation for 2.8.

### CODE REVIEW

**Comment by kabalin** [comment]
Rebased on latest 2.8 code, in fact this may be redundant, see suggestion in #16

**Comment by agwells** [comment]
I'll merge it into the moodle28 branch, and then I'll turn the moodle28 branch into the new "master" branch.

**Comment by kabalin** [comment]
Feel free to use this one, https://github.com/lucisgit/moodle-assignsubmission_mahara/commit/7a74f63726c9c4d7907560a5a9d9ecce84fce88c it is aleady 2.7 compatible (i.e. required version reduced).

**Comment by agwells** [comment]
Done.

**Comment by kabalin** [comment]
Thanks! Any change you could release next version during Mahara HUI UK? Should not be much work, I have updated README already.

**Comment by agwells** [comment]
Yep, I'm working on it right now. I'll see if I can get it ready in the next couple of hours. I just need to give it a quick test first.

**Comment by agwells** [comment]
Hi Ruslan,
FYI, I've gotten the release up: https://moodle.org/plugins/pluginversion.php?id=9707
Cheers,
Aaron

**Comment by agwells** [comment]
And I also unlisted the feedback plugin from Moodle 2.7 & 2.8, since it's no longer needed. And updated all the plugin descriptions accordingly.

**Comment by kabalin** [comment]
Thanks Aaron!

**Pull request closed without merging**
